server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/OrderDb
    username: postgres
    password: 1234

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans