spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092
    template:
      observation-enabled: true

      listener:
        observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/OrderDb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 2

      InventoryClientreleaseInventoryLong:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s

  retry:
    instances:

      InventoryClientreserveInventoryInventoryRequest:
        max-attempts: 3
        wait-duration: 1s

      InventoryClientreleaseInventoryLong:
        max-attempts: 3
        wait-duration: 1s

  timelimiter:
    instances:

      InventoryClientreserveInventoryInventoryRequest:
        timeout-duration: 3s

      InventoryClientreleaseInventoryLong:
        timeout-duration: 3s

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always


  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %m%n"


jwt:
  secret: "my-super-secret-key-my-super-secret-key-123456"